[project]
name = "caainp-cvm"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "caainp-csm",
    "easyocr",
    "hf_xet",
    "loguru",
    "matplotlib",
    "networkx",
    "numpy",
    "open-clip-torch",
    "opencv-contrib-python",
    "pandas",
    "pillow",
    "scikit-image",
    "scikit-learn",
    "seaborn",
    "shapely",
    "tokenizers",
    "torch==2.5.1",
    "torchvision==0.20.1",
    "transformers",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
caainp-csm = { git = "https://github.com/caainp/caainp-csm.git" }
torch = { index = "pytorch-cpu" }
torchvision = { index = "pytorch-cpu" }

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.hatch.build.targets.wheel]
packages = ["caainp_cvm", "scripts"]

[tool.hatch.build.targets.wheel.force-include]
"ai_4f_node_map_fixed_embeded.csv" = "caainp_cvm/data/ai_4f_node_map_fixed_embeded.csv"
"node_images/node_images" = "caainp_cvm/data/node_images"
