from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any, Iterable, Sequence, Mapping

import math
import networkx as nx
from loguru import logger


# ---------------------------------------------------------------------
# Type definitions
# ---------------------------------------------------------------------

ValueMapDict = Dict[str, Any]


@dataclass
class ValueMapResult:
    """
    Data structure returned from CVM to NAV/CSM as a value map.

    Attributes
    ----------
    current_node : int
        Node id estimated as the current position.
    neighbor_values : Dict[int, float]
        Mapping from neighbor node id to a normalized value in [0, 1].
    debug : Dict[str, Dict[int, float]]
        Intermediate scores for debugging (e.g. route_score, visited_penalty).
    """
    current_node: int
    neighbor_values: Dict[int, float]
    debug: Dict[str, Dict[int, float]]

    def to_dict(self) -> ValueMapDict:
        return {
            "current_node": int(self.current_node),
            "neighbor_values": {
                int(k): float(v) for k, v in self.neighbor_values.items()
            },
            "debug": {
                name: {int(k): float(v) for k, v in scores.items()}
                for name, scores in self.debug.items()
            },
        }


@dataclass
class ValueMapParams:
    """
    Weight configuration for ValueMap v2.

    Currently only route vs visual weights are used. In later phases,
    visit / obstacle factors can also be introduced.
    """
    w_route: float = 0.9   # weight for route-based score
    w_visual: float = 0.1  # weight for CLIP / visual-based score


@dataclass
class ValueMapState:
    """
    Per-session state for ValueMap that persists across frames.

    Attributes
    ----------
    visit_counts : Dict[int, int]
        How many times each node has been chosen as a candidate "visit".
    """
    visit_counts: Dict[int, int] = field(default_factory=dict)

    def increment_visit(self, node_id: int) -> None:
        self.visit_counts[node_id] = self.visit_counts.get(node_id, 0) + 1


# ---------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------

def _build_route_index(route_nodes: Iterable[int]) -> Dict[int, int]:
    """
    Build an index map from node id to its position in the route.

    Example
    -------
    [401, 4102, 4101] -> {401: 0, 4102: 1, 4101: 2}
    """
    return {int(n): idx for idx, n in enumerate(route_nodes)}


def _estimate_current_index(
    route_index: Dict[int, int],
    current_node: int,
) -> Optional[int]:
    """
    Estimate where the current_node lies on the route.

    Returns
    -------
    Optional[int]
        Index of current_node in the route, or None if current_node
        is not part of the route.
    """
    current_node = int(current_node)
    return route_index.get(current_node, None)


def _compute_visited_set(
    route_index: Dict[int, int],
    idx_current: Optional[int],
) -> Dict[int, bool]:
    """
    Approximate the set of nodes that have already been passed.

    Rules
    -----
    - If idx_current is given: nodes with index <= idx_current are visited.
    - If idx_current is None: no node is considered visited.
    """
    visited: Dict[int, bool] = {}
    if idx_current is None:
        for n in route_index.keys():
            visited[int(n)] = False
        return visited

    for n, idx in route_index.items():
        visited[int(n)] = bool(idx <= idx_current)
    return visited


# ---------------------------------------------------------------------
# Phase 1: basic route-based value map
# ---------------------------------------------------------------------

def build_value_map(
    *,
    current_node: int,
    route_nodes: List[int],
    target_nodes: List[int],
    graph: nx.Graph,
    visited_nodes_override: Optional[Iterable[int]] = None,
    gamma_route: float = 0.7,
    visited_penalty_value: float = 0.3,
) -> ValueMapDict:
    """
    Phase 1: build a route-based ValueMap (no yaw/depth/obstacle yet).

    Parameters
    ----------
    current_node : int
        Node id estimated by CVM as the current position.
    route_nodes : List[int]
        Route of the current step generated by CSM.
        Example: [401, 4102, 4101, 4105, 4106, 4150]
    target_nodes : List[int]
        Target nodes of this step (usually one node).
    graph : nx.Graph
        Graph created by map_loader.load_map_csv(...).
    visited_nodes_override : Optional[Iterable[int]]
        Explicit set of visited nodes. If None, it is inferred from
        route_nodes and current_node.
    gamma_route : float
        Decay rate when converting remaining steps to value.
        Larger value increases the gap between near and far nodes
        with respect to the goal.
    visited_penalty_value : float
        Penalty factor for nodes considered "already passed" (0~1).

    Returns
    -------
    ValueMapDict
        {
            "current_node": int,
            "neighbor_values": {neighbor_node: value},
            "debug": {
                "route_score": {...},
                "visited_penalty": {...},
                "raw_value": {...},
            }
        }
    """
    current_node = int(current_node)
    route_nodes = [int(n) for n in route_nodes]
    target_nodes = [int(n) for n in target_nodes]

    # 0) gather neighbors of current_node
    if current_node not in graph:
        raise ValueError(f"current_node {current_node} is not in graph")

    neighbors = [int(nbr) for nbr in graph.neighbors(current_node)]
    if not neighbors:
        logger.warning(f"Node {current_node} has no neighbors in graph")
        return ValueMapResult(
            current_node,
            {},
            {
                "route_score": {},
                "visited_penalty": {},
                "raw_value": {},
            },
        ).to_dict()

    # 1) build route index
    route_index = _build_route_index(route_nodes)
    idx_current = _estimate_current_index(route_index, current_node)

    # 2) determine goal index (use last target on the route)
    idx_goal_candidates: List[int] = [
        route_index[t] for t in target_nodes if t in route_index
    ]
    if idx_goal_candidates:
        idx_goal = max(idx_goal_candidates)
    else:
        # if no target is on the route, treat the last route node as goal
        idx_goal = max(route_index.values())

    # 3) determine visited set
    if visited_nodes_override is not None:
        visited_set = {int(n): True for n in visited_nodes_override}
    else:
        visited_set = _compute_visited_set(route_index, idx_current)

    route_score: Dict[int, float] = {}
    visited_penalty: Dict[int, float] = {}
    raw_value: Dict[int, float] = {}

    # 4) compute scores for each neighbor
    max_raw = 0.0

    for nbr in neighbors:
        # 4-1) route-based score
        if nbr in route_index:
            idx_nbr = route_index[nbr]
            steps_to_goal = max(idx_goal - idx_nbr, 0)
            score = math.exp(-gamma_route * steps_to_goal)
        else:
            # nodes outside the route get a small default score
            score = math.exp(-gamma_route * (len(route_nodes) + 1))

        route_score[nbr] = score

        # 4-2) visited penalty
        if visited_set.get(nbr, False):
            vp = visited_penalty_value
        else:
            vp = 1.0
        visited_penalty[nbr] = vp

        # 4-3) final raw value
        v = score * vp
        raw_value[nbr] = v
        if v > max_raw:
            max_raw = v

    # 5) normalize into [0, 1]
    neighbor_values: Dict[int, float] = {}
    if max_raw > 0:
        for nbr, v in raw_value.items():
            neighbor_values[nbr] = v / max_raw
    else:
        # fallback: uniform distribution if all values are zero
        uniform = 1.0 / len(neighbors)
        for nbr in neighbors:
            neighbor_values[nbr] = uniform

    result = ValueMapResult(
        current_node=current_node,
        neighbor_values=neighbor_values,
        debug={
            "route_score": route_score,
            "visited_penalty": visited_penalty,
            "raw_value": raw_value,
        },
    )
    return result.to_dict()


# ---------------------------------------------------------------------
# Phase 2: route + visual + history + obstacle
# ---------------------------------------------------------------------

def build_value_map_v2(
    *,
    current_node: int,
    route_nodes: Sequence[int],
    target_nodes: Sequence[int],
    graph,
    cvm_candidates: Optional[Sequence[Mapping[str, Any]]] = None,
    blocked_edges=None,
    params: Optional[ValueMapParams] = None,
) -> Dict[str, Any]:
    """
    Phase 2 ValueMap.

    Extends Phase 1 (build_value_map) by:
    - reusing route_score / visited_penalty from Phase 1,
    - injecting CLIP-based candidates from cvm_result as a visual factor,
    - applying history_factor (direction along the route) and
      obstacle_penalty (blocked edges) to compute the final score.

    Parameters
    ----------
    current_node : int
        Current node id.
    route_nodes : Sequence[int]
        Route nodes of this step, generated by CSM.
    target_nodes : Sequence[int]
        Target nodes of this step.
    graph : nx.Graph
        Graph created by map_loader.load_map_csv(...).
    cvm_candidates : Optional[Sequence[Mapping[str, Any]]]
        candidates list from localize_image(), e.g.
        [{"node_id": 4102, "score": 0.18}, ...]
    blocked_edges : Optional[Iterable[Tuple[int, int]]]
        List of edges that are considered blocked due to obstacles.
        For example: [(4102, 435), (4102, 434)].
    params : Optional[ValueMapParams]
        Weight configuration for route / visual fusion.

    Returns
    -------
    dict
        {
          "current_node": int,
          "neighbor_values": {neighbor_node: 0~1 score},
          "debug": {... intermediate scores ...}
        }
    """
    if params is None:
        params = ValueMapParams()

    # 1) Phase 1 base result
    base = build_value_map(
        current_node=current_node,
        route_nodes=list(route_nodes),
        target_nodes=list(target_nodes),
        graph=graph,
    )

    neighbors = list(base["neighbor_values"].keys())
    route_score: Dict[int, float] = base["debug"]["route_score"]
    visited_penalty: Dict[int, float] = base["debug"]["visited_penalty"]
    base_raw: Dict[int, float] = base["debug"]["raw_value"]

    # 2) visual factor from CVM candidates
    visual_raw: Dict[int, float] = {nid: 0.0 for nid in neighbors}

    if cvm_candidates:
        # candidates: [{"node_id": 4102, "score": 0.18}, ...]
        cand_map: Dict[int, float] = {}
        for c in cvm_candidates:
            try:
                nid = int(c.get("node_id"))
                s = float(c.get("score"))
            except (TypeError, ValueError):
                continue
            # if multiple entries exist, keep the maximum score for safety
            cand_map[nid] = max(cand_map.get(nid, 0.0), s)

        for nid in neighbors:
            visual_raw[nid] = cand_map.get(int(nid), 0.0)

    # 3) normalize visual_raw to [0, 1] → visual_align
    if neighbors:
        v_values = [visual_raw[n] for n in neighbors]
        v_min = min(v_values)
        v_max = max(v_values)
        denom = (v_max - v_min) or 1.0

        if v_max == v_min:
            # no meaningful visual variation → treat as zeros
            visual_align: Dict[int, float] = {nid: 0.0 for nid in neighbors}
        else:
            visual_align = {
                nid: (visual_raw[nid] - v_min) / denom
                for nid in neighbors
            }
    else:
        visual_align = {}

    # 4) clamp route_score to [0, 1] → route_norm
    route_norm: Dict[int, float] = {}
    for nid in neighbors:
        r = float(route_score.get(nid, 0.0))
        if r < 0.0:
            r = 0.0
        if r > 1.0:
            r = 1.0
        route_norm[nid] = r

    # 5) history_factor: forward / backward / off-route
    #
    # Example:
    #   route_nodes       = [401, 4102, 4106, 4150]
    #   route_index_map   = {401:0, 4102:1, 4106:2, 4150:3}
    #   current_node=4102 → idx_cur = 1
    #
    #   - same or ahead (idx_nbr >= idx_cur) → 1.0
    #   - behind (idx_nbr < idx_cur) → exp(-gamma_back * steps_back)
    #   - off-route nodes → off_route_default
    route_index_map: Dict[int, int] = {}
    for idx, nid in enumerate(route_nodes):
        route_index_map[int(nid)] = idx

    idx_cur = route_index_map.get(int(current_node), 0)

    gamma_back = 0.7
    off_route_default = 0.7

    history_factor: Dict[int, float] = {}
    for nid in neighbors:
        nid_int = int(nid)
        if nid_int in route_index_map:
            idx_nbr = route_index_map[nid_int]
            if idx_nbr >= idx_cur:
                hist = 1.0
            else:
                steps_back = idx_cur - idx_nbr
                hist = math.exp(-gamma_back * steps_back)
        else:
            hist = off_route_default
        history_factor[nid] = hist

    # 6) obstacle_penalty from blocked_edges
    #
    #   - if blocked_edges is None/empty → all edges have penalty 1.0
    #   - if (current_node, neighbor) is blocked → apply strong penalty
    blocked_set = set()
    if blocked_edges:
        for e in blocked_edges:
            if not e:
                continue
            try:
                u, v = e
            except Exception:
                continue
            try:
                u = int(u)
                v = int(v)
            except ValueError:
                continue
            if u == v:
                continue
            if u > v:
                u, v = v, u
            blocked_set.add((u, v))

    OBSTACLE_FACTOR_BLOCKED = 0.05

    obstacle_penalty: Dict[int, float] = {}
    cur_int = int(current_node)
    for nid in neighbors:
        nid_int = int(nid)
        a, b = (cur_int, nid_int) if cur_int <= nid_int else (nid_int, cur_int)
        if (a, b) in blocked_set:
            obstacle_penalty[nid] = OBSTACLE_FACTOR_BLOCKED
        else:
            obstacle_penalty[nid] = 1.0

    # 7) combine route_norm, visual_align, visited_penalty,
    #    history_factor, obstacle_penalty into a single score.
    #
    #    combined_score[n] =
    #        (w_route * route_norm[n] + w_visual * visual_align[n])
    #        * visited_penalty[n]
    #        * history_factor[n]
    #        * obstacle_penalty[n]
    #
    #    Then normalize combined_score to [0, 1] → neighbor_values.
    combined_score: Dict[int, float] = {}
    for nid in neighbors:
        r = route_norm.get(nid, 0.0)
        v = visual_align.get(nid, 0.0)
        vp = float(visited_penalty.get(nid, 1.0))
        hist = float(history_factor.get(nid, 1.0))
        obs = float(obstacle_penalty.get(nid, 1.0))

        base_score = params.w_route * r + params.w_visual * v
        if base_score < 0.0:
            base_score = 0.0

        s = base_score * vp * hist * obs
        combined_score[nid] = s

    neighbor_values: Dict[int, float] = {}
    if neighbors:
        max_score = max(combined_score.values()) if combined_score else 0.0
        if max_score > 0.0:
            for nid in neighbors:
                neighbor_values[nid] = combined_score[nid] / max_score
        else:
            # fallback: uniform distribution if all scores are zero
            uniform = 1.0 / len(neighbors)
            for nid in neighbors:
                neighbor_values[nid] = uniform

    # 8) debug payload
    debug = {
        "route_score": route_score,
        "visited_penalty": visited_penalty,
        "raw_value": base_raw,
        "visual_raw": visual_raw,
        "visual_align": visual_align,
        "route_norm": route_norm,
        "combined_score": combined_score,
        "history_factor": history_factor,
        "obstacle_penalty": obstacle_penalty,
        "route_index_map": route_index_map,
        "idx_cur": idx_cur,
    }

    return {
        "current_node": current_node,
        "neighbor_values": neighbor_values,
        "debug": debug,
    }
